#
# MIT License
# Copyright (c) 2021 Orange
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the  Software), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
#

included:
  - OrangeDesignSystem
  - OrangeDesignSystemDemo/OrangeDesignSystemDemo
  - InnovationCupTheme
  - OrangeTheme
excluded:
  - OrangeDesignSystemDemo/OrangeDesignSystemDemo/Resources

disabled_rules:
  - trailing_comma
  - cyclomatic_complexity
  - file_length
  - force_unwrapping
  - function_body_length
  - function_parameter_count
  - identifier_name
  - inclusive_language
  - line_length
  - opening_brace
  - orphaned_doc_comment
  - type_body_length
  - type_name
  - xctfail_message

opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - balanced_xctest_lifecycle
  - capture_variable
  # - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  # - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_assert
  - discarded_notification_center_observer
  # - discouraged_none_name
  - discouraged_object_literal
  # - discouraged_optional_boolean
  # - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  # - enum_case_associated_values_count
  - expiring_todo
  # - explicit_acl
  # - explicit_enum_raw_value
  - explicit_init
  - explicit_self
  # - explicit_top_level_acl
  # - explicit_type_interface
  # - extension_access_modifier
  - fallthrough
  - fatal_error_message
  # - file_header
  # - file_name
  - file_name_no_space
  # - file_types_order
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  # - function_default_parameter_at_end
  - ibinspectable_in_extension
  - identical_operands
  # - implicit_return
  # - implicitly_unwrapped_optional
  # - indentation_width
  - joined_default_parameter
  - last_where
  - legacy_multiple
  # - legacy_objc_type
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  # - missing_docs
  - modifier_order
  # - multiline_arguments
  # - multiline_arguments_brackets
  # - multiline_function_chains
  # - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - no_extension_access_modifier
  # - no_grouping_extension
  - no_space_in_method_call
  - nslocalizedstring_key
  # - nslocalizedstring_require_bundle
  - number_separator
  # - object_literal
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  # - prefer_nimble
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  # - prefixed_toplevel_constant
  - private_action
  # - private_outlet
  - private_subject
  # - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  # - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  # - required_deinit
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  # - strict_fileprivate
  - strong_iboutlet
  # - switch_case_on_newline
  - test_case_accessibility
  - toggle_bool
  # - trailing_closure
  # - type_contents_order
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_declaration
  - unused_import
  # - vertical_parameter_alignment_on_call
  # - vertical_whitespace_between_cases
  # - vertical_whitespace_closing_braces
  # - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition
