#
# Software Name: Orange Design System (iOS)
# SPDX-FileCopyrightText: Copyright (c) 2021 - 2023 Orange SA
# SPDX-License-Identifier: MIT
#
# This software is distributed under the MIT license.
#

use_frameworks!

platform :ios, '15.0'

target 'OrangeDesignSystemDemo' do
  pod 'Parma'
  target 'OrangeDesignSystemDemoTests' do
    inherit! :search_paths

    pod 'SwiftLint', '0.48.0'
    pod 'SwiftFormat/CLI'
    
  end
end

post_install do |installer|
  ENV['COCOAPODS_DISABLE_STATS'] = "true"
  
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["DEAD_CODE_STRIPPING"] = "YES"
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings['SWIFT_VERSION'] = '5'
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"      
    end
  end
end
