#
# Software Name: Orange Design System (iOS)
# SPDX-FileCopyrightText: Copyright (c) 2021-2023 Orange SA
# SPDX-License-Identifier: MIT
#
# This software is distributed under the MIT license.
#

APPLE_ISSUER_ID = ENV["ODS_APPLE_ISSUER_ID"]
APPLE_KEY_ID = ENV["ODS_APPLE_KEY_ID"]
APPLE_KEY_CONTENT = ENV["ODS_APPLE_KEY_CONTENT"]
DEVELOPER_APP_IDENTIFIER = ENV["ODS_DEVELOPER_APP_IDENTIFIER"]

MATTERMOST_HOOK_URL = ENV["ODS_MATTERMOST_HOOK_URL"]
MATTERMOST_HOOK_BOT_NAME = ENV["ODS_MATTERMOST_HOOK_BOT_NAME"]
MATTERMOST_HOOK_BOT_ICON_URL = ENV["ODS_MATTERMOST_HOOK_BOT_ICON_URL"]

ODS_WORKSPACE = "OrangeDesignSystemDemo.xcworkspace"
ODS_PROJECT = "OrangeDesignSystemDemo.xcodeproj"
ODS_SCHEME = "OrangeDesignSystemDemo"
ODS_PROPROFILE = ENV["ODS_PROPROFILE"]

default_platform(:ios)

platform :ios do

  # ------------------------------------------------------------
  # UPDATE BUILD NUMBER WITH TIMESTAMP
  # ------------------------------------------------------------
  desc "UPDATE BUILD NUMBER WITH TIMESTAMP"
  lane :increment do
    timestamp = sh 'date +%s'
    timestamp = timestamp.strip!
    increment_build_number(xcodeproj: ODS_PROJECT, build_number: timestamp)
  end

  # ------------------------------------------------------------
  # READ AND SET NEXT RELEASE NOTE IN CHANLOG
  # ------------------------------------------------------------
  desc "READ AND SET NEXT RELEASE NOTE IN CHANLOG"
  lane :prepare_release do
    version = get_app_version

    stamp_changelog(
        changelog_path: '../CHANGELOG.md',
        section_identifier: version,
        git_tag: version,
        should_stamp_date: true,
        stamp_datetime_format: '%F'
    )
  end

  # ------------------------------------------------------------
  # BUILD DEBUG APP
  # ------------------------------------------------------------
  desc "BUILD DEBUG APP"
  lane :buildDebugApp do
    cocoapods(
      clean_install: true
    )
    gym(
      scheme: ODS_SCHEME,
      output_directory: 'build/',
      archive_path: 'build/',
      output_name: 'odsApp',
      configuration: 'Debug',
      include_symbols: true,
      export_method: 'development'
    )
  end

  # ------------------------------------------------------------
  # BUILD & UPLOAD TO TESTFLIGHT QUALIF APP
  # ------------------------------------------------------------
  desc "BUILD & UPLOAD TO TESTFLIGHT QUALIF APP"
  lane :qualif do
    puts "This is a dumb 'puts' to ensure the 'Appfile' is read!"
    Dir.chdir "../OrangeDesignSystemDemo/Resources/Assets.xcassets" do
        sh "rm -Rf AppIconRelease.appiconset"
        sh "cp -R AppIconQualif.appiconset AppIconRelease.appiconset"
    end

    set_info_plist_value(path: "#{Dir.pwd}/../OrangeDesignSystemDemo/Resources/Info.plist", key: "ODSBuildType", value: "BETA")
    
    build_and_upload(upload: true)
  end

  # ------------------------------------------------------------
  # BUILD & UPLOAD TO TESTFLIGHT PROD APP
  # ------------------------------------------------------------
  desc "BUILD & UPLOAD TO TESTFLIGHT (if set in options: upload) PROD APP"
  lane :prod do |options|
    puts "This is a dumb 'puts' to ensure the 'Appfile' is read!"
    build_and_upload(options)
  end

  # -----------------------------------------------------------------------
  # PRIVATE LANE BUILD & UPLOAD (DEV / QUALIF / PROD is set by main lane)
  # -----------------------------------------------------------------------
  private_lane :build_and_upload do |options|
    build

    if options[:upload]
      upload
    else
      puts ">> Upload to testflight no requested"
    end
  end

  # -----------------------------------------------------------------------
  # PRIVATE LANE BUILD (DEV / QUALIF / PROD is set by main lane)
  # -----------------------------------------------------------------------
  desc "PRIVATE LANE BUILD (DEV / QUALIF / PROD is set by main lane)"
  private_lane :build do
    begin
        update_app_identifier(
            xcodeproj: "#{ODS_PROJECT}",
            plist_path: "OrangeDesignSystemDemo/Resources/Info.plist",
            app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
        )

        increment

        cocoapods(
            clean_install: true
        )

        build_app(
            workspace: ODS_WORKSPACE,
            clean: true,
            scheme: ODS_SCHEME,
            output_directory: 'build/',
            archive_path: 'build/odsApp.xcarchive',
            output_name: 'odsApp',
            configuration: 'Release',
            include_symbols: true,
            export_method: 'app-store',
            xcargs: '-allowProvisioningUpdates'
        )
        
        publish_mattermost_notification("🔨 ✅ @channel A new build has been done successfully")

    rescue => error
        publish_mattermost_notification("🔨 🚨 @channel An issue occurred during the build step (:build_and_upload)")
        raise error
    end
  end
  
  # -----------------------------------------------------------------------
  # PRIVATE LANE UPLOAD TO TESTFLIGHT (DEV / QUALIF / PROD is set by main lane)
  # -----------------------------------------------------------------------
  desc "PRIVATE LANE UPLOAD TO TESTFLIGHT"
  private_lane :upload do
    begin
        api_key = app_store_connect_api_key(
          key_id: APPLE_KEY_ID,
          issuer_id: APPLE_ISSUER_ID,
          key_content: APPLE_KEY_CONTENT,
          duration: 500,
          in_house: false
        )
        
        TESTFLIGHT_GROUPS = ENV['TESTFLIGHT_GROUPS']
        
        version = get_app_version
        puts version

        build_number = get_build_number(xcodeproj: ODS_PROJECT)
        puts build_number

        news = read_current_release_notes

        upload_to_testflight(
            changelog: news,
            app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
            skip_submission: false,
            skip_waiting_for_build_processing: false,
            distribute_external: true,
            notify_external_testers: true,
            groups: TESTFLIGHT_GROUPS,
            api_key: api_key
        )
        
        publish_mattermost_notification("☁️ ✅ @channel The upload to TestFlight has been done successfully")
    rescue => error
        publish_mattermost_notification("☁️ 🚨 @channel An issue occurred during the upload step (:build_and_upload)")
        raise error
    end
  end
  
  # -----------------------------------------
  # PRIVATE LANE FOR MATTERMOST NOTIFICATIONS
  # -----------------------------------------
  def publish_mattermost_notification(message)
      mattermost(url: MATTERMOST_HOOK_URL,
                 text: message,
                 username: MATTERMOST_HOOK_BOT_NAME,
                 icon_url: MATTERMOST_HOOK_BOT_ICON_URL
                 )
  end

  # -------
  # Helpers
  # -------
  # Get version set in the Xcode project
  def get_app_version
    version = get_version_number(
        xcodeproj: ODS_PROJECT,
        target: ODS_SCHEME
    )
    return version
  end

  # Read release note in section associated to the current version
  # If empty, try within the Unreleased section
  def read_current_release_notes
    version = get_app_version

    changelog=read_changelog(
        changelog_path: '../CHANGELOG.md',
        section_identifier: "[#{version}]",
    )

    if changelog == ""
        changelog=read_changelog(
            changelog_path: '../CHANGELOG.md',
            section_identifier: "[Unreleased]",
        )
    end

    puts "current relase notes = #{changelog}"
    return changelog
  end

end

