name: Documentation Update
description: Describe this issue found in the documentation
title: "[Doc]: "
labels: ["documentation", "triage"]
assignees: 
  - B3nz01d
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: location
    attributes:
      label: Documentation Location
      description: Where in the documentation should there be an update.
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Current issue
      description: A description of what is currently in the doc.
    validations:
      required: true
  - type: textarea
    id: correction
    attributes:
      label: Expected Correction
      description: A clear and concise description of what you expected to be updated.
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
