# If you update this file, please also update _config_netlify.yml with the exact same changes
plugins:
- jekyll-feed
- jekyll-relative-links
relative_links:
  enabled: true
  collections: true
remote_theme: Orange-OpenSource/ods-jekyll-theme
baseurl: /ods-ios
defaults:
  - scope:
      path: ""
    values:
      version: ""
  - scope:
      path: "1.1.0"
    values:
      version: "1.1.0"
  - scope:
      path: "1.0.0"
    values:
      version: "1.0.0"
